proyectoDjangu/app/urls.py
from django.urls import path, include
from .views import home, contacto, galeria, agregar_producto, listar_producto, modificar_producto, eliminar_producto, registro, ProductoViewset
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewset)



urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('galeria/', galeria, name="galeria"),
    path('agregar-producto/', agregar_producto, name='agregar_producto'),
    path('listar-productos/', listar_producto, name='listar_producto'),
    path('modificar-producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar-producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('registro/', registro, name="registro"),
    path('api/', include(router.urls)),
] 


proyectoDjangu/proyectoDjangu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoDjangu/app/models.py
from django.db import models

# Create your models here.
class Marca(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    descripcion = models.TextField()
    nuevo = models.BooleanField()
    marca = models.ForeignKey(Marca, on_delete=models.PROTECT)
    fecha_fabricacion = models.DateField()
    imagen = models.ImageField(upload_to="productos", null=True)

    def __str__(self):
        return self.nombre
opciones_consulta = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]
]


class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()

proyectoDjangu/app/forms.py
from django import forms
from .models import Contacto, Producto
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ContactoForm(forms.ModelForm):

    class Meta:
        model = Contacto
        fields = '__all__'

class ProductoForm(forms.ModelForm):

    nombre = forms.CharField(min_length=3, max_length=50)
    imagen = forms.ImageField(required=False)

    class Meta:
        model = Producto
        fields = '__all__'

        widgets = {
            "fecha_fabricacion": forms.SelectDateWidget()
        }
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', "first_name", "last_name", "email", "password1", "password2"]
        

proyectoDjangu/app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto
from .forms import ContactoForm, ProductoForm, CustomUserCreationForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import viewsets
from .serializers import ProductoSerializer

# Create your views here.

class ProductoViewset(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer

    def get_queryset(self):
        productos = Producto.objects.all()

        nombre = self.request.GET.get('nombre')

        if nombre:
            productos = productos.filter(nombre=nombre)
        return productos

def home(request):
    productos = Producto.objects.all()
    data = {
        'productos': productos
    }

    return render(request, 'app/home.html', data)

def contacto(request):
    data = {
        'form': ContactoForm()
    }

    if request.method == 'POST':
        formulario = ContactoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "ADOPCION ENVIADA!!"
        else:
            data["form"] = formulario

    return render(request, 'app/contacto.html', data)

def galeria(request):
    return render(request, 'app/galeria.html')

@permission_required('app.add_producto')
def agregar_producto(request):

    data = {
        'form': ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "PRODUCTO SOLICITADO")
        else:
            data["form"] = formulario

    return render(request, 'app/producto/agregar.html', data)

@permission_required('app.view_producto')
def listar_producto(request):
    productos = Producto.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(productos, 5)
        productos = paginator.page(page)
    except:
        raise Http404

    data = {
        'entity': productos,
        'paginator': paginator
    }

    return render(request, 'app/producto/listar.html', data)
@permission_required('app.delete_producto')
def modificar_producto(request, id):

    producto = get_object_or_404(Producto, id=id)

    data = {
        'form': ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "editado correctamente")
            return redirect(to="listar_producto")
        data["form"] = formulario


    return render(request, 'app/producto/modificar.html', data)

def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    messages.success(request, "Producto eliminado")
    return redirect(to="listar_producto")

def registro(request):
    data = {
        'form': CustomUserCreationForm()
    }
    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "REGISTRO EXITOSO ")
            return redirect(to="home")
        data["form"] = formulario


    return render(request, 'registration/registro.html', data)

proyectoDjangu/app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>proyecto</title>
    <link
        href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap"
        rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'app/css/estilos.css' %}">

</head>

<body>

    <header id="header">
        <img class="menu" src="{% static 'app/img/menuiconwhite.png' %}" alt="menu" id="menu">
        <div class="contenedor_logo">
            <img class="logo" src="{% static 'app/img/tecnomarketpngicono.png' %}" alt="logo">
        </div>

        <div>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'home' %}"> INICIO </a>
                    </li>
                    <li>
                        <a href="{% url 'contacto' %}">contactanos</a>
                    </li>
                    <li><a href="{% url 'galeria' %}">adopta!</a></li>
                    {% if perms.app.add_producto %}
                    <li>
                        <a href="{% url 'agregar_producto' %}">solicita tu producto</a>
                    </li>
                    {% endif %}
                    {% if perms.app.view_producto %}
                    <li>
                        <a href="{% url 'listar_producto' %}">productos solicitados</a>
                    </li>
                    <li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'logout' %}">cerrar sesion</a>
                    </li>
                    <li>
                        <a href="#">{{ user.username }}</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}">iniciar sesion</a>
                    </li>
                    <li>
                        <a href="{% url 'registro' %}">registrar usuario</a>
                    </li>

                    {% endif %}
                    </li>
                </ul>
            </nav>

        </div>

    </header>

    <div id="contenido">

        {% block contenido%}
        {% endblock %}

    </div>


    <footer>
        <div class="marcas">
            <img src="{% static 'app/img/footer/apple.png' %}" alt="Bulterrier">
            <img src="{% static 'app/img/footer/lenovo.png' %}" alt="Pastor">
            <img src="{% static 'app/img/footer/microsoft.png' %}" alt="pudeel">
            <img src="{% static 'app/img/footer/samsung.png' %}" alt="galgo">
            <img src="{% static 'app/img/footer/xiaomi.png' %}" alt="pitbul">
        </div>
        <div class="logo_footer">
            <img src="{% static 'app/img/tecnomarketpngicono.png' %}" alt="logo">
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'app/js/menu.js' %}"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
    {% for m in messages %}
    <script>
        Swal.fire({
            "title": "Lo has conseguido!!",
            "text": "{{m}}",
            "icon": "success"
        })

    </script>
    {% endfor %}
    {% endif %}
    {% block js %}
    {% endblock %}



</body>

</html>

proyectoDjangu/app/templates/app/contacto.html
{% extends 'app/base.html'%}

{% block contenido %}
{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                <h2>ENVIA TU FORMULARIO PARA ADOPTAR</h2>
                <form action="" class="" method="post">

                    {% csrf_token %}

                    {{ form | crispy }}
                    <hr>
                    <br>

                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>

                    </div>

                </form>
                {{mensaje}}

            </div>
        </div>

    </div>
</div>
<table id="tablacontactos">

</table>

{% endblock %}

proyectoDjangu/app/templates/app/galeria.html
{% extends 'app/base.html'%}
{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>


{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />


{% endblock %}

{% block contenido %}

<h1>PERROS EN ADOPCION!!!</h1>
<br><br>
<div class="galeria">
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda1.jpg' %}"><img src="{% static 'app/img/tienda/tienda1.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda2.jpeg' %}"><img src="{% static 'app/img/tienda/tienda2.jpeg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda3.jpg' %}"><img src="{% static 'app/img/tienda/tienda3.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda4.jpg' %}"><img src="{% static 'app/img/tienda/tienda4.jpg' %}"></a>
    <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda5.jpg' %}"><img src="{% static 'app/img/tienda/tienda5.jpg' %}"></a>     
</div>

{% endblock %}

proyectoDjangu/app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

<script>
    $(document).ready(function () {
        $('.slider').bxSlider({
            mode: 'fade',//horizontal, vertical, fade
            auto: true,
            pause: 2000
        });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">

{% endblock %}


<div class="slider">
    <div>
        <img src="{% static 'app/img/banner/banner1.png' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner2.png' %}" alt="">
    </div>
    <div>
        <img src="{% static 'app/img/banner/banner3.png' %}" alt="">
    </div>
</div>
{% load humanize %}
<h2>Perros en Adopcion !!</h2>
<div class="productos">
    {% for p in productos %}
    <div class="producto">

        <div class="contenedor_producto">
            {% if p.imagen %}
            <img src="{{ p.imagen.url }}" alt="imagen producto">
            {% endif %}
            <div class="detalle">
                <h5>{{ p.marca | capfirst }}</h5>
                <h2>{{ p.nombre | title }} </h2>
                <h3>{{p.precio | intcomma }}</h3>
            </div>

        </div>

    </div>
    {% endfor %}

</div>

proyectoDjangu/app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

proyectoDjangu/app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-body">
                        <h2>REQUIERE TU PRODUCTO</h2>
                        <hr>
                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}

                            <div class="d-flex justify-content-end">
                                <input type="reset" value="Cancelar" class="btn btn-secondary">
                                <input type="submit" value="guardar" class="btn btn-prymary">

                            </div>
                        </form>
                        {{mensaje}}

                    </div>

                </div>
            </div>
        </div>
{% endblock %}

proyectoDjangu/app/templates/app/producto/listar.html
{% extends 'app/base.html' %}

{% block js %}

    <script>
        function eliminarproducto(id){
            Swal.fire({
                "title": "¿Estas seguro de eliminar?",
                "text": "no se puede volver atras",
                "icon": "question",
                "showCancelButton":true,
                "cancelButtonText": "NO, Cancelar",
                "confirmButtonText": "si , eliminar"
            })
            .then(function(result) {
                if(result.isConfirmed) {
                    window.location.href = "/eliminar-producto/"+id+"/"
                }
            })
        }
    </script>

{% endblock %}

{% block contenido %}
{% load humanize %}
<br>
<div class="card">
    <div class="card-body">
        <h2>PRODUCTOS DISPONIBLES PARA VENTAS</h2>
        <table class="table table-striped table-hover table-responsive-sm">
            <hr>
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>¿Nuevo?</th>
                <th>Opciones</th>
            </tr>
        
            {% for p in entity %}
        
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>${{ p.precio | intcomma }}</td>
                <td>{{ p.marca | title }}</td>
                <td>
                    {% if p.nuevo %}
                    SI
                    {% else %}
                    NO
                    {% endif %}
                </td>
                <td>
                    {% if perms.app.change_producto %}
                    <a href="{% url 'modificar_producto' p.id %}" class="btn btn-info">modificar</a>
                    {% endif %}
                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarproducto({{ p.id }})" class="btn btn-danger">eliminar</a>
                    {% endif %}
                </td>
        
            </tr>
            {% endfor %}
        
        </table>
        <div>
            {% include 'app/paginator.html' %}
        </div>
    </div>
</div>


{% endblock %}

proyectoDjangu/app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-body">
                        <h2>EDITA TU PRODUCTO</h2>
                        <hr>
                        <form action="" method="post" enctype="multipart/form-data">

                            {% csrf_token %}
                            {{ form | crispy }}

                            <div class="d-flex justify-content-end">
                                <input type="reset" value="Cancelar" class="btn btn-secondary">
                                <input type="submit" value="Modificar" class="btn btn-prymary">

                            </div>
                        </form>
                        {{mensaje}}


                    </div>

                </div>
            </div>
        </div>
{% endblock %}